class TaskType < ActiveRecord::Base
  has_many :tasks
  belongs_to :role

  TASK_TYPE_PLAN_CUENTA_MARKUP = 1
  TASK_TYPE_PLAN_RESUMEN_MARKUP = 2
  TASK_TYPE_PLAN_DS_MARKUP = 3
  TASK_TYPE_PLAN_GENERIC_MARKUP = 4
  TASK_TYPE_PLAN_CORRECTION = 5
  TASK_TYPE_PLAN_POST_DS_MARKUP = 6
  TASK_TYPE_PLAN_POBLAMIENTO = 7

  TASK_TYPE_MARK_CUENTA_MARKUP = 10
  TASK_TYPE_MARK_RESUMEN_MARKUP = 20
  TASK_TYPE_MARK_DS_MARKUP = 30
  TASK_TYPE_MARK_GENERIC_MARKUP = 40

  TASK_TYPE_VERIFY_CUENTA_MARKUP = 100
  TASK_TYPE_VERIFY_RESUMEN_MARKUP = 200
  TASK_TYPE_VERIFY_DS_MARKUP = 300
  TASK_TYPE_VERIFY_GENERIC_MARKUP = 400
end
